# Generated by Django 6.0.3 on 2026-04-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('comum', 'Usuário Comum'), ('organizador', 'Organizador de Eventos'), ('admin', 'Administrador')], default='comum', max_length=20),
        ),
    ]
