# Generated by Django 6.0.3 on 2026-04-10 04:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('saude', 'Saúde'), ('educacao', 'Educação'), ('cultura', 'Cultura'), ('esporte', 'Esporte'), ('assistencia_social', 'Assistência Social'), ('meio_ambiente', 'Meio Ambiente'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('vagas', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField()),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Social',
                'verbose_name_plural': 'Eventos Sociais',
                'ordering': ['data_hora'],
            },
        ),
    ]
