# Generated by Django 6.0.3 on 2026-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosocial',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
