# Generated by Django 6.0.3 on 2026-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventosocial_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosocial',
            name='endereco_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventosocial',
            name='categoria',
            field=models.CharField(choices=[('saude', 'Saúde'), ('educacao', 'Educação'), ('cultura', 'Cultura'), ('esporte', 'Esporte'), ('assistencia_social', 'Assistência Social'), ('meio_ambiente', 'Meio Ambiente'), ('tecnologia', 'Tecnologia'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
    ]
