# Generated by Django 6.0.3 on 2026-07-05 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventosocial_endereco_texto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='events.eventosocial')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Evento',
                'verbose_name_plural': 'Avaliações de Eventos',
                'constraints': [models.UniqueConstraint(fields=('evento', 'participante'), name='unique_avaliacao_por_participante_evento'), models.CheckConstraint(condition=models.Q(('nota__gte', 1), ('nota__lte', 5)), name='avaliacao_nota_entre_1_e_5')],
            },
        ),
    ]
